public class Main {
    public static void main(String[] args) {
        System.out.println("Задание №1");
        byte small = 126;
        System.out.println("Самое маленькое целое значение " + small);
        short normal = 130;
        System.out.println("Среднее целое значение " + normal);
        int big = 33000;
        System.out.println("Большое целое значение " + big);
        long veryBig = 2147484000L;
        System.out.println("Самое большое целое значение " + veryBig);
        float smolDifference = 21.134875614f;
        System.out.println("Малое не целое " + smolDifference);
        double bigDifference = 21.124234234234;
        System.out.println("Большое не целое " + bigDifference);

        System.out.println("Задание №2");
        float one = 27.12f;
        System.out.println("Первое число по заданию " + one);
        long two = 987678965549L;
        System.out.println("Второе число по заданию " + two);
        double three = 2.786;
        System.out.println("Третье число по заданию " + three);
        short four = 569;
        System.out.println("Четвертое число по заданию " + four);
        short five = -159;
        System.out.println("Пятое число по заданию " + five);
        int six = 27897;
        System.out.println("Шестое число по заданию " + six);
        byte sewen = 67;
        System.out.println("Седьмое число по заданию " + sewen);

        System.out.println("Задание №3");
        byte lyudmila = 23;
        byte anna =27;
        byte ekaterina = 30;
        short paper = 480;
        int students = lyudmila + anna + ekaterina;
        int studentsPaper = paper/students;
        System.out.println("Общее количество учеников " + students);
        System.out.println("Бумаги для каждого ученика " + studentsPaper);

        System.out.println("Задание №4");
        byte irrationalCountingBottle = 16;
        byte irrationalCountingTime = 2;
        int bottle = irrationalCountingBottle/irrationalCountingTime;
        System.out.println("Производительность машины за 1 минуту " + bottle);
        byte twentyMinutes = 20;
        int bottleTwentyMinutes = bottle * twentyMinutes;
        System.out.println("За " + twentyMinutes + " минут машина произвела " + bottleTwentyMinutes + " штук бутылок");
        int hour = twentyMinutes * 3;
        int day = hour * 24;
        int bottleDay = bottle * day;
        System.out.println("За сутки = " + day + " минут, машина произвела " + bottleDay + " штук бутылок");
        int threeDay = day * 3;
        int bottleThreeDay = bottle * threeDay;
        System.out.println("За трое суток = "+threeDay+" минут, машина произвела "+bottleThreeDay+" штук бутылок");
        int monthVeryShort = day * 28;
        int monthNotVeryShort = day * 29;
        int monthShort = day * 30;
        int monthLong = day * 31;
        int bottleMonth1 = bottle * monthVeryShort;
        System.out.println("За февраль = "+monthVeryShort+" минут, машина произвела "+bottleMonth1+" штук бутылок");
        int bottleMonth2 = bottle * monthNotVeryShort;
        System.out.println("За весакосный февраль = "+monthNotVeryShort+" минут, машина произвела "+bottleMonth2+" штук бутылок");
        int bottleMonth3 = bottle * monthShort;
        System.out.println("За месяц (30 дней) = "+monthShort+" минут, машина произвела "+bottleMonth3+" штук бутылок");
        int bottleMonth4 = bottle * monthLong;
        System.out.println("За месяц (31 день) = "+monthLong+" минут, машина произвела "+bottleMonth4+" штук бутылок");

        System.out.println("Задание №5");
        byte cansOfPaint = 120;
        byte whiteCansForKlass = 2;
        byte brownCansForKlass = 4;
        int cansForKlass = whiteCansForKlass + brownCansForKlass;
        System.out.println("Для класса надо "+cansForKlass+" банок краски");
        int klass = cansOfPaint/cansForKlass;
        System.out.println("Всего классов в школе "+klass);
        int klassWhite = klass * whiteCansForKlass;
        int klassBrown = klass * brownCansForKlass;
        System.out.println("В школе где "+klass+" классов, нужно "+klassWhite+" банок белой краски и "+klassBrown+" банок коричневой краски");

        System.out.println("Задание №6");
        byte oneBanana = 80;
        byte milk100Gram = 105;
        byte oneSundae = 100;
        byte oneEgg = 70;
        int banana = oneBanana * 5;
        int milk = milk100Gram * 2;
        int sundae = oneSundae * 2;
        int egg = oneEgg * 4;
        int cocktail = banana + milk + sundae +egg;
        System.out.println("Коктейль весит "+cocktail+ "грам");
        float kilogram = cocktail/1000F;
        System.out.println("Коктейль в килограммах весит "+kilogram+" кг");

        System.out.println("Задание №7");
        byte rules = 7;
        short lang = 250;
        short faster = 500;
        int rulesGram = rules*1000;
        int more = rulesGram/lang;
        System.out.println("Если сбрасывает по 250 грам в день то понадобится "+more+" дней");
        int less = rulesGram/faster;
        System.out.println("Если сбрасывает по 500 грам в день то понадобится "+less+" дней");
        int average = (more+less)/2;
        System.out.println("Если питается по разному "+average+" день");

        System.out.println("Задание №8");
        int masha = 67760;
        int denis = 83690;
        int kristina = 76230;
        float mashaNew = masha+(masha * 0.1f);
        int mashaOldYear = masha * 12;
        float mashaNewYear = mashaNew * 12;
        float mashaDifference = mashaNewYear  - mashaOldYear;
        System.out.println("Маша теперь получает "+mashaNew+" рублей. Годовой доход вырос на "+mashaDifference);
        float denisNew = denis+(denis * 0.1f);
        int denisOldYear = denis * 12;
        float denisNewYear = denisNew * 12;
        float denisDifference = denisNewYear  - denisOldYear;
        System.out.println("Маша теперь получает "+denisNew+" рублей. Годовой доход вырос на "+denisDifference);
        float kristinaNew = kristina+(kristina * 0.1f);
        int kristinaOldYear = kristina * 12;
        float kristinaNewYear = kristinaNew * 12;
        float kristinaDifference = kristinaNewYear  - kristinaOldYear;
        System.out.println("Маша теперь получает "+kristinaNew+" рублей. Годовой доход вырос на "+kristinaDifference);
    }
}