public class Main {
    public static void main(String[] args) {
        System.out.println("Задание №1");
        byte Small = 126;
        System.out.println("Самое маленькое целое значение " + Small);
        short Normal = 130;
        System.out.println("Среднее целое значение " + Normal);
        int Big = 33000;
        System.out.println("Большое целое значение " + Big);
        long VeryBig = 2147484000L;
        System.out.println("Самое большое целое значение " + VeryBig);
        float SmolDifference = 21.134875614f;
        System.out.println("Малое не целое " + SmolDifference);
        double big_difference = 21.124234234234;
        System.out.println("Большое не целое " + big_difference);

        System.out.println("Задание №2");
        float One = 27.12f;
        System.out.println("Первое число по заданию " + One);
        long Two = 987678965549L;
        System.out.println("Второе число по заданию " + Two);
        double Three = 2.786;
        System.out.println("Третье число по заданию " + Three);
        short Four = 569;
        System.out.println("Четвертое число по заданию " + Four);
        short Five = -159;
        System.out.println("Пятое число по заданию " + Five);
        int Six = 27897;
        System.out.println("Шестое число по заданию " + Six);
        byte Sewen = 67;
        System.out.println("Седьмое число по заданию " + Sewen);

        System.out.println("Задание №3");
        byte Lyudmila = 23;
        byte Anna =27;
        byte Ekaterina = 30;
        short Paper = 480;
        int Students = Lyudmila + Anna + Ekaterina;
        int StudentsPaper = Paper/Students;
        System.out.println("Общее количество учеников " + Students);
        System.out.println("Бумаги для каждого ученика " + StudentsPaper);

        System.out.println("Задание №4");
        byte IrrationalCountingBottle = 16;
        byte IrrationalCountingTime = 2;
        int Bottle = IrrationalCountingBottle/IrrationalCountingTime;
        System.out.println("Производительность машины за 1 минуту " + Bottle);
        byte TwentyMinutes = 20;
        int BottleTwentyMinutes = Bottle * TwentyMinutes;
        System.out.println("За " + TwentyMinutes + " минут машина произвела " + BottleTwentyMinutes + " штук бутылок");
        int Hour = TwentyMinutes * 3;
        int Day = Hour * 24;
        int BottleDay = Bottle * Day;
        System.out.println("За сутки = " + Day + " минут, машина произвела " + BottleDay + " штук бутылок");
        int ThreeDay = Day * 3;
        int BottleThreeDay = Bottle * ThreeDay;
        System.out.println("За трое суток = "+ThreeDay+" минут, машина произвела "+BottleThreeDay+" штук бутылок");
        int MonthVeryShort = Day * 28;
        int MonthNotVeryShort = Day * 29;
        int MonthShort = Day * 30;
        int MonthLong = Day * 31;
        int BottleMonth1 = Bottle * MonthVeryShort;
        System.out.println("За февраль = "+MonthVeryShort+" минут, машина произвела "+BottleMonth1+" штук бутылок");
        int BottleMonth2 = Bottle * MonthNotVeryShort;
        System.out.println("За весакосный февраль = "+MonthNotVeryShort+" минут, машина произвела "+BottleMonth2+" штук бутылок");
        int BottleMonth3 = Bottle * MonthShort;
        System.out.println("За месяц (30 дней) = "+MonthShort+" минут, машина произвела "+BottleMonth3+" штук бутылок");
        int BottleMonth4 = Bottle * MonthLong;
        System.out.println("За месяц (31 день) = "+MonthLong+" минут, машина произвела "+BottleMonth4+" штук бутылок");

        System.out.println("Задание №5");
        byte CansOfPaint = 120;
        byte WhiteCansForKlass = 2;
        byte BrownCansForKlass = 4;
        int CansForKlass = WhiteCansForKlass + BrownCansForKlass;
        System.out.println("Для класса надо "+CansForKlass+" банок краски");
        int Klass = CansOfPaint/CansForKlass;
        System.out.println("Всего классов в школе "+Klass);
        int KlassWhite = Klass * WhiteCansForKlass;
        int KlassBrown = Klass * BrownCansForKlass;
        System.out.println("В школе где "+Klass+" классов, нужно "+KlassWhite+" банок белой краски и "+KlassBrown+" банок коричневой краски");

        System.out.println("Задание №6");
        byte OneBanana = 80;
        byte Milk100Gram = 105;
        byte OneSundae = 100;
        byte OneEgg = 70;
        int Banana = OneBanana * 5;
        int Milk = Milk100Gram * 2;
        int Sundae = OneSundae * 2;
        int Egg = OneEgg * 4;
        int Cocktail = Banana + Milk + Sundae +Egg;
        System.out.println("Коктейль весит "+Cocktail+ "грам");
        float Kilogram = Cocktail/1000F;
        System.out.println("Коктейль в килограммах весит "+Kilogram+" кг");

        System.out.println("Задание №7");
        byte Rules = 7;
        short Long = 250;
        short Faster = 500;
        int RulesGram = Rules*1000;
        int More = RulesGram/Long;
        System.out.println("Если сбрасывает по 250 грам в день то понадобится "+More+" дней");
        int Less = RulesGram/Faster;
        System.out.println("Если сбрасывает по 500 грам в день то понадобится "+Less+" дней");
        int Average = (More+Less)/2;
        System.out.println("Если питается по разному "+Average+" день");

        System.out.println("Задание №8");
        int Masha = 67760;
        int Denis = 83690;
        int Kristina = 76230;
        float MashaNew = Masha+(Masha * 0.1f);
        int MashaOldYear = Masha * 12;
        float MashaNewYear = MashaNew * 12;
        float MashaDifference = MashaNewYear  - MashaOldYear;
        System.out.println("Маша теперь получает "+MashaNew+" рублей. Годовой доход вырос на "+MashaDifference);
        float DenisNew = Denis+(Denis * 0.1f);
        int DenisOldYear = Denis * 12;
        float DenisNewYear = DenisNew * 12;
        float DenisDifference = DenisNewYear  - DenisOldYear;
        System.out.println("Маша теперь получает "+DenisNew+" рублей. Годовой доход вырос на "+DenisDifference);
        float KristinaNew = Kristina+(Kristina * 0.1f);
        int KristinaOldYear = Kristina * 12;
        float KristinaNewYear = KristinaNew * 12;
        float KristinaDifference = KristinaNewYear  - KristinaOldYear;
        System.out.println("Маша теперь получает "+KristinaNew+" рублей. Годовой доход вырос на "+KristinaDifference);
    }
}